name: Java CI

on: [push, pull_request]

jobs:
  build-ac:
    name: AC Test with Java ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['11', '17', '21' ]

    steps:
      - uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.jdk }}
          cache: 'maven'

      - name: Test with Maven
        run: mvn -B verify
  build-unittest:
    name: Unit Test with Java ${{ matrix.jdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['11', '17', '21' ]

    steps:
      - uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: ${{ matrix.jdk }}
          cache: 'maven'
      - name: Test with Maven
        run: mvn -B test -Dgroups='!acceptance'
